### ISSUE TITLE
Line highlight doesn't work as expected

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/requirements-template#4]
See https://github.com/netwerk-digitaal-erfgoed/requirements-datasets/commit/661b6150ef2bf395263c254fc73181ef1e5e94a1#commitcomment-42288478

Seems `line-highlight="3,5"` highlights lines 3 and 5, but `line-highlight="11-15"` **doesn't** highlight lines 3 thru 5...

**Comment by ddeboer** [comment]
https://github.com/netwerk-digitaal-erfgoed/requirements-datasets/commit/486ead568a3e4c516faa227dc18a155a7f7675a3 [works fine](https://netwerk-digitaal-erfgoed.github.io/requirements-datasets/#dataset-basic).
