### ISSUE TITLE
Github action does not produce .html

### ISSUE THREAD

**Issue by mielvds** [netwerk-digitaal-erfgoed/requirements-template#5]
Hi! I started using the template [here](https://github.com/ErfgoedPod/usecases) and [here](https://github.com/ErfgoedPod/common-setups), but it fails to generate the html in the `gh-pages` branch. Any idea what would cause this? It works locally.

**Comment by ddeboer** [comment]
Cool! I see that you’re [gitignoring](https://github.com/ErfgoedPod/usecases/blob/master/.gitignore) `*.html`. That definitely makes sense for ignoring locally built `index.html` but also breaks the publishing workflow to GitHub Pages.

So, a workaround is to remove `*.html` from your `.gitignore`. I’ll try to find a way to keep that `.gitignore` without breaking publication.

**Comment by mielvds** [comment]
oh djeez. Thanks!
